image_config: &image_config
  IMAGE_NAME: azure-fn-deploy

  IMAGE_TAG: latest
  LINUX_VERSION: UBUNTU_XENIAL
  PYTHON_VERSION_NUM: 3.7.1
  JAVA: false
  MYSQL_CLIENT: false
  POSTGRES_CLIENT: false
  DOCKERIZE: false
  BROWSERS: false
version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config
    steps:
      - checkout
      - run: bash scripts/generate.sh > Dockerfile
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 10
      - store_artifacts:
          path: Dockerfile
  test_image:
    docker:
      - image: $DOCKER_USERNAME/azure-fn-deploy:latest
        environment:
          <<: *image_config
    steps:
      - checkout
      - run:
          name: bats tests
          command: |
            mkdir -p test_results/bats
            bats scripts/tests.bats | \
            perl scripts/tap-to-junit.sh > \
            test_results/bats/results.xml
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build:
          context: org-global
      - test_image:
          context: org-global
          requires:
            - build